// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JoinGroup struct {
	UserID  string `json:"userId"`
	GroupID string `json:"groupId"`
}

type NewGroup struct {
	Name string `json:"name"`
}

type NewKey struct {
	Content string `json:"content"`
	Name    string `json:"name"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	Name     *string `json:"name"`
	Username string  `json:"username"`
}
